# Pull clean small base runtime container
FROM nginx:alpine

# Purge default static elements and deploy customized content
COPY index.html /usr/share/nginx/html/

# Declare listener application operational target
EXPOSE 8000
